# Generated by Django 5.2.17 on 2026-09-10 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('periodos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='fecha')),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('ADVERTENCIA', 'advertencia'), ('INCONSISTENTE', 'inconsistente'), ('AUSENTE', 'ausente'), ('JUSTIFICADO', 'justificado'), ('FERIADO', 'feriado'), ('LIBRE', 'libre')], db_index=True, max_length=14, verbose_name='estado')),
                ('horario_snapshot', models.JSONField(blank=True, default=list, verbose_name='horario esperado')),
                ('marcas_usadas', models.JSONField(blank=True, default=list, verbose_name='marcas usadas')),
                ('minutos_esperados', models.IntegerField(default=0, verbose_name='esperados')),
                ('minutos_trabajados', models.IntegerField(default=0, verbose_name='trabajados')),
                ('minutos_ordinarios', models.IntegerField(default=0, verbose_name='ordinarios')),
                ('minutos_extra', models.IntegerField(default=0, verbose_name='extra')),
                ('minutos_tardia', models.IntegerField(default=0, verbose_name='tardia')),
                ('minutos_salida_anticipada', models.IntegerField(default=0, verbose_name='salida anticipada')),
                ('minutos_no_laborados', models.IntegerField(default=0, verbose_name='no laborados')),
                ('minutos_fuera_horario', models.IntegerField(default=0, verbose_name='fuera de horario')),
                ('minutos_feriado', models.IntegerField(default=0, verbose_name='feriado')),
                ('minutos_descanso_trabajado', models.IntegerField(default=0, verbose_name='descanso trabajado')),
                ('observaciones', models.JSONField(blank=True, default=list, verbose_name='observaciones')),
                ('aceptado_en', models.DateTimeField(blank=True, null=True, verbose_name='aceptado en')),
                ('motivo_aceptacion', models.TextField(blank=True, verbose_name='motivo de aceptacion')),
                ('calculado_en', models.DateTimeField(auto_now=True, verbose_name='calculado en')),
                ('aceptado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dias_aceptados', to=settings.AUTH_USER_MODEL, verbose_name='aceptado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.empleado', verbose_name='empleado')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='periodos.periodo', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'resultado diario',
                'verbose_name_plural': 'resultados diarios',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['empleado', 'fecha'], name='motor_resul_emplead_2e3c02_idx'), models.Index(fields=['estado'], name='motor_resul_estado_85def3_idx')],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'fecha'), name='resultado_unico_por_empleado_y_dia')],
            },
        ),
    ]
