# Generated by Django 5.2.17 on 2026-09-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('api_key_hash', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('api_key_prefijo', models.CharField(blank=True, max_length=16)),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso')),
            ],
            options={
                'verbose_name': 'cliente de API',
                'verbose_name_plural': 'clientes de API',
                'ordering': ['nombre'],
            },
        ),
    ]
