# Generated by Django 5.2.17 on 2026-09-10 20:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMarcaManual',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('fecha_local', models.DateField(db_index=True, verbose_name='fecha local')),
                ('motivo', models.CharField(choices=[('olvido', 'olvido'), ('reloj_fuera_servicio', 'reloj fuera de servicio'), ('trabajo_externo', 'trabajo externo'), ('error_marca', 'error de marca'), ('otro', 'otro')], max_length=30, verbose_name='motivo')),
                ('detalle', models.TextField(verbose_name='detalle')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobada', 'aprobada'), ('rechazada', 'rechazada'), ('anulada', 'anulada')], default='pendiente', max_length=12, verbose_name='estado')),
                ('creada_en', models.DateTimeField(blank=True, editable=False, verbose_name='creada en')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True, verbose_name='resuelta en')),
                ('comentario_resolucion', models.TextField(blank=True, verbose_name='comentario de resolucion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empleado', verbose_name='empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='resuelta por')),
            ],
            options={
                'verbose_name': 'historical marca manual',
                'verbose_name_plural': 'historical marcas manuales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMarcaReloj',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=30, verbose_name='PersonID')),
                ('person_name', models.CharField(blank=True, max_length=60, verbose_name='nombre en el reloj')),
                ('card_no', models.CharField(blank=True, max_length=30, verbose_name='tarjeta')),
                ('utc_ms', models.BigIntegerField(verbose_name='hora UTC en milisegundos')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('fecha_local', models.DateField(db_index=True, verbose_name='fecha local')),
                ('state', models.IntegerField(default=0, verbose_name='AttendanceState')),
                ('method', models.IntegerField(default=0, verbose_name='metodo')),
                ('device_ip', models.CharField(blank=True, default='', max_length=20, verbose_name='IP del dispositivo')),
                ('device_name', models.CharField(blank=True, max_length=50, verbose_name='dispositivo')),
                ('snapshot_path', models.CharField(blank=True, max_length=200, verbose_name='ruta de la foto')),
                ('handler', models.CharField(blank=True, max_length=50, verbose_name='modificada en SmartPSS por')),
                ('remarks', models.CharField(blank=True, max_length=256, verbose_name='observaciones del reloj')),
                ('recibida_en', models.DateTimeField(blank=True, editable=False, verbose_name='recibida en')),
                ('anulada', models.BooleanField(default=False, verbose_name='anulada')),
                ('anulada_en', models.DateTimeField(blank=True, null=True, verbose_name='anulada en')),
                ('motivo_anulacion', models.TextField(blank=True, verbose_name='motivo de anulacion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('anulada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='anulada por')),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empleado', verbose_name='empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sucursal', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'historical marca del reloj',
                'verbose_name_plural': 'historical marcas del reloj',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MarcaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('fecha_local', models.DateField(db_index=True, verbose_name='fecha local')),
                ('motivo', models.CharField(choices=[('olvido', 'olvido'), ('reloj_fuera_servicio', 'reloj fuera de servicio'), ('trabajo_externo', 'trabajo externo'), ('error_marca', 'error de marca'), ('otro', 'otro')], max_length=30, verbose_name='motivo')),
                ('detalle', models.TextField(verbose_name='detalle')),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobada', 'aprobada'), ('rechazada', 'rechazada'), ('anulada', 'anulada')], default='pendiente', max_length=12, verbose_name='estado')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True, verbose_name='resuelta en')),
                ('comentario_resolucion', models.TextField(blank=True, verbose_name='comentario de resolucion')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcas_manuales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcas_manuales', to='core.empleado', verbose_name='empleado')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marcas_manuales_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='resuelta por')),
            ],
            options={
                'verbose_name': 'marca manual',
                'verbose_name_plural': 'marcas manuales',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['empleado', 'fecha_local'], name='marcas_marc_emplead_59d347_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarcaReloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=30, verbose_name='PersonID')),
                ('person_name', models.CharField(blank=True, max_length=60, verbose_name='nombre en el reloj')),
                ('card_no', models.CharField(blank=True, max_length=30, verbose_name='tarjeta')),
                ('utc_ms', models.BigIntegerField(verbose_name='hora UTC en milisegundos')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('fecha_local', models.DateField(db_index=True, verbose_name='fecha local')),
                ('state', models.IntegerField(default=0, verbose_name='AttendanceState')),
                ('method', models.IntegerField(default=0, verbose_name='metodo')),
                ('device_ip', models.CharField(blank=True, default='', max_length=20, verbose_name='IP del dispositivo')),
                ('device_name', models.CharField(blank=True, max_length=50, verbose_name='dispositivo')),
                ('snapshot_path', models.CharField(blank=True, max_length=200, verbose_name='ruta de la foto')),
                ('handler', models.CharField(blank=True, max_length=50, verbose_name='modificada en SmartPSS por')),
                ('remarks', models.CharField(blank=True, max_length=256, verbose_name='observaciones del reloj')),
                ('recibida_en', models.DateTimeField(auto_now_add=True, verbose_name='recibida en')),
                ('anulada', models.BooleanField(default=False, verbose_name='anulada')),
                ('anulada_en', models.DateTimeField(blank=True, null=True, verbose_name='anulada en')),
                ('motivo_anulacion', models.TextField(blank=True, verbose_name='motivo de anulacion')),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marcas_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='anulada por')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marcas', to='core.empleado', verbose_name='empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcas', to='core.sucursal', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'marca del reloj',
                'verbose_name_plural': 'marcas del reloj',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['empleado', 'fecha_local'], name='marcas_marc_emplead_63517f_idx'), models.Index(fields=['fecha_local'], name='marcas_marc_fecha_l_b97f8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'person_id', 'utc_ms', 'device_ip'), name='marca_unica_por_sucursal')],
            },
        ),
    ]
