# Generated by Django 5.2.17 on 2026-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcareloj',
            name='device_ip',
            field=models.CharField(blank=True, default='', help_text='SmartPSS llama IP a esta columna, pero el reloj escribe su numero de serie (BA00C34PAJ426F2). Se conserva el nombre del campo porque es el de la tabla de SmartPSS.', max_length=20, verbose_name='serie del dispositivo'),
        ),
    ]
