# Generated by Django 5.2.17 on 2026-09-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='fecha')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('tolerancia_entrada_min', models.PositiveIntegerField(default=5, help_text='Minutos de atraso que se perdonan.', verbose_name='tolerancia de entrada')),
                ('minimo_extra_min', models.PositiveIntegerField(default=15, help_text='Desde cuantos minutos despues de la salida se cuenta extra.', verbose_name='minimo para extra')),
                ('ventana_duplicado_min', models.PositiveIntegerField(default=5, help_text='Dos marcas mas juntas que esto se cuentan como una sola.', verbose_name='ventana de duplicados')),
                ('contar_llegada_temprana', models.BooleanField(default=False, help_text='Si llegar antes de la hora se paga como extra.', verbose_name='contar llegada temprana')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'lunes'), (1, 'martes'), (2, 'miercoles'), (3, 'jueves'), (4, 'viernes'), (5, 'sabado'), (6, 'domingo')], verbose_name='dia de la semana')),
                ('orden', models.PositiveSmallIntegerField(choices=[(1, 'bloque 1'), (2, 'bloque 2')], verbose_name='orden')),
                ('hora_entrada', models.TimeField(verbose_name='hora de entrada')),
                ('hora_salida', models.TimeField(verbose_name='hora de salida')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='horarios.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'bloque de horario',
                'verbose_name_plural': 'bloques de horario',
                'ordering': ['dia_semana', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('horario', 'dia_semana', 'orden'), name='bloque_unico_por_dia')],
            },
        ),
    ]
