# Generated by Django 5.2.17 on 2026-09-10 20:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='fecha')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('tipo_jornada', models.CharField(choices=[('diurna', 'diurna'), ('mixta', 'mixta'), ('nocturna', 'nocturna')], default='diurna', max_length=10, verbose_name='tipo de jornada')),
                ('tolerancia_entrada_min', models.PositiveIntegerField(default=5, verbose_name='tolerancia de entrada')),
                ('minimo_extra_min', models.PositiveIntegerField(default=15, verbose_name='minimo para extra')),
                ('ventana_duplicado_min', models.PositiveIntegerField(default=5, verbose_name='ventana de duplicados')),
                ('contar_llegada_temprana', models.BooleanField(default=False, verbose_name='contar llegada temprana')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFeriado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='fecha')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical feriado',
                'verbose_name_plural': 'historical feriados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHorario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='nombre')),
                ('tipo_jornada', models.CharField(choices=[('diurna', 'diurna'), ('mixta', 'mixta'), ('nocturna', 'nocturna')], default='diurna', max_length=10, verbose_name='tipo de jornada')),
                ('tolerancia_entrada_min', models.PositiveIntegerField(default=5, verbose_name='tolerancia de entrada')),
                ('minimo_extra_min', models.PositiveIntegerField(default=15, verbose_name='minimo para extra')),
                ('ventana_duplicado_min', models.PositiveIntegerField(default=5, verbose_name='ventana de duplicados')),
                ('contar_llegada_temprana', models.BooleanField(default=False, verbose_name='contar llegada temprana')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical horario',
                'verbose_name_plural': 'historical horarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJustificacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'vacaciones'), ('incapacidad', 'incapacidad'), ('permiso_con_goce', 'permiso con goce'), ('permiso_sin_goce', 'permiso sin goce'), ('otro', 'otro')], max_length=20, verbose_name='tipo')),
                ('desde', models.DateField(verbose_name='desde')),
                ('hasta', models.DateField(verbose_name='hasta')),
                ('detalle', models.TextField(blank=True, verbose_name='detalle')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empleado', verbose_name='empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrada_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'historical justificacion',
                'verbose_name_plural': 'historical justificaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBloqueHorario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'lunes'), (1, 'martes'), (2, 'miercoles'), (3, 'jueves'), (4, 'viernes'), (5, 'sabado'), (6, 'domingo')], verbose_name='dia de la semana')),
                ('orden', models.PositiveSmallIntegerField(choices=[(1, 'bloque 1'), (2, 'bloque 2')], verbose_name='orden')),
                ('hora_entrada', models.TimeField(verbose_name='hora de entrada')),
                ('hora_salida', models.TimeField(verbose_name='hora de salida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='horarios.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'historical bloque de horario',
                'verbose_name_plural': 'historical bloques de horario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAsignacionHorario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empleado', verbose_name='empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='horarios.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'historical asignacion de horario',
                'verbose_name_plural': 'historical asignaciones de horario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(verbose_name='vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.empleado', verbose_name='empleado')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='horarios.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'asignacion de horario',
                'verbose_name_plural': 'asignaciones de horario',
                'ordering': ['empleado__nombre', '-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'vacaciones'), ('incapacidad', 'incapacidad'), ('permiso_con_goce', 'permiso con goce'), ('permiso_sin_goce', 'permiso sin goce'), ('otro', 'otro')], max_length=20, verbose_name='tipo')),
                ('desde', models.DateField(verbose_name='desde')),
                ('hasta', models.DateField(verbose_name='hasta')),
                ('detalle', models.TextField(blank=True, verbose_name='detalle')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='core.empleado', verbose_name='empleado')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'justificacion',
                'verbose_name_plural': 'justificaciones',
                'ordering': ['-desde'],
            },
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'lunes'), (1, 'martes'), (2, 'miercoles'), (3, 'jueves'), (4, 'viernes'), (5, 'sabado'), (6, 'domingo')], verbose_name='dia de la semana')),
                ('orden', models.PositiveSmallIntegerField(choices=[(1, 'bloque 1'), (2, 'bloque 2')], verbose_name='orden')),
                ('hora_entrada', models.TimeField(verbose_name='hora de entrada')),
                ('hora_salida', models.TimeField(verbose_name='hora de salida')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='horarios.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'bloque de horario',
                'verbose_name_plural': 'bloques de horario',
                'ordering': ['dia_semana', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('horario', 'dia_semana', 'orden'), name='bloque_unico_por_dia')],
            },
        ),
    ]
