# Generated by Django 5.2.17 on 2026-09-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_planilla', models.CharField(help_text='El identificador que usa planillas. Nunca cambia.', max_length=30, unique=True, verbose_name='codigo de planilla')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('identificacion', models.CharField(blank=True, max_length=30, verbose_name='identificacion')),
                ('person_id_smartpss', models.CharField(blank=True, help_text='El numero con que el reloj identifica a esta persona.', max_length=30, null=True, unique=True, verbose_name='PersonID en SmartPSS')),
                ('departamento', models.CharField(blank=True, max_length=60, verbose_name='departamento')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='fecha de salida')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='horarios.horario', verbose_name='horario')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['person_id_smartpss'], name='core_emplea_person__bbacaf_idx')],
            },
        ),
    ]
