# Generated by Django 5.2.17 on 2026-09-10 20:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo_agente', models.CharField(help_text='Debe coincidir con AGENTE_NOMBRE en el .env del agente.', max_length=50, unique=True, verbose_name='codigo del agente')),
                ('api_key_hash', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('api_key_prefijo', models.CharField(blank=True, max_length=16)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True, verbose_name='ultima sincronizacion')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('supervisores', models.ManyToManyField(blank=True, related_name='departamentos_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='supervisores')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='core.sucursal', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['sucursal__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmpleado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_planilla', models.CharField(db_index=True, help_text='Identificador que usa el sistema de planillas. Nunca cambia.', max_length=30, verbose_name='codigo de planilla')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('identificacion', models.CharField(blank=True, max_length=30, verbose_name='identificacion')),
                ('person_id_smartpss', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='PersonID en SmartPSS')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='fecha de salida')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.departamento', verbose_name='departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical empleado',
                'verbose_name_plural': 'historical empleados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_planilla', models.CharField(help_text='Identificador que usa el sistema de planillas. Nunca cambia.', max_length=30, unique=True, verbose_name='codigo de planilla')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('identificacion', models.CharField(blank=True, max_length=30, verbose_name='identificacion')),
                ('person_id_smartpss', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='PersonID en SmartPSS')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='fecha de salida')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.departamento', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['person_id_smartpss'], name='core_emplea_person__bbacaf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nombre'), name='departamento_unico_por_sucursal'),
        ),
    ]
