# Generated by Django 5.2.17 on 2026-09-10 20:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriodo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('desde', models.DateField(verbose_name='desde')),
                ('hasta', models.DateField(verbose_name='hasta')),
                ('estado', models.CharField(choices=[('abierto', 'abierto'), ('en_revision', 'en revision'), ('cerrado', 'cerrado')], default='abierto', max_length=12, verbose_name='estado')),
                ('cerrado_en', models.DateTimeField(blank=True, null=True, verbose_name='cerrado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cerrado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cerrado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical periodo',
                'verbose_name_plural': 'historical periodos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('desde', models.DateField(verbose_name='desde')),
                ('hasta', models.DateField(verbose_name='hasta')),
                ('estado', models.CharField(choices=[('abierto', 'abierto'), ('en_revision', 'en revision'), ('cerrado', 'cerrado')], default='abierto', max_length=12, verbose_name='estado')),
                ('cerrado_en', models.DateTimeField(blank=True, null=True, verbose_name='cerrado en')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='cerrado por')),
            ],
            options={
                'verbose_name': 'periodo',
                'verbose_name_plural': 'periodos',
                'ordering': ['-desde'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAjuste',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_original', models.DateField(verbose_name='fecha original')),
                ('concepto', models.CharField(choices=[('ordinarios', 'ordinarios'), ('extra', 'extra'), ('feriado', 'feriado'), ('descanso_trabajado', 'descanso trabajado'), ('tardia', 'tardia'), ('no_laborados', 'no laborados')], max_length=20, verbose_name='concepto')),
                ('minutos', models.IntegerField(help_text='Puede ser negativo.', verbose_name='minutos')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('creado_en', models.DateTimeField(blank=True, editable=False, verbose_name='creado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.empleado', verbose_name='empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodo_destino', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='periodos.periodo', verbose_name='periodo destino')),
            ],
            options={
                'verbose_name': 'historical ajuste',
                'verbose_name_plural': 'historical ajustes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_original', models.DateField(verbose_name='fecha original')),
                ('concepto', models.CharField(choices=[('ordinarios', 'ordinarios'), ('extra', 'extra'), ('feriado', 'feriado'), ('descanso_trabajado', 'descanso trabajado'), ('tardia', 'tardia'), ('no_laborados', 'no laborados')], max_length=20, verbose_name='concepto')),
                ('minutos', models.IntegerField(help_text='Puede ser negativo.', verbose_name='minutos')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='core.empleado', verbose_name='empleado')),
                ('periodo_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='periodos.periodo', verbose_name='periodo destino')),
            ],
            options={
                'verbose_name': 'ajuste',
                'verbose_name_plural': 'ajustes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
